services:
  api:
    build: ./lambda
    ports:
      - "3001:3001"
    env_file:
      - path: .env.local
        required: false
    environment:
      - INDEX_PATH=/data/icon-index.sqlite
    volumes:
      - ./lambda/src:/app/src
      - ./data:/data

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - api
    environment:
      - API_PROXY_TARGET=http://api:3001
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - ./frontend/public:/app/public
